/*
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCalScopeProvider extends DelegatingScopeProvider {
}
