/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import streamblocks.eclipse.cal.cal.AstProcessDescription;
import streamblocks.eclipse.cal.cal.AstStatement;
import streamblocks.eclipse.cal.cal.CalPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ast Process Description</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.impl.AstProcessDescriptionImpl#isRepeated <em>Repeated</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.impl.AstProcessDescriptionImpl#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AstProcessDescriptionImpl extends MinimalEObjectImpl.Container implements AstProcessDescription
{
  /**
   * The default value of the '{@link #isRepeated() <em>Repeated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRepeated()
   * @generated
   * @ordered
   */
  protected static final boolean REPEATED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRepeated() <em>Repeated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRepeated()
   * @generated
   * @ordered
   */
  protected boolean repeated = REPEATED_EDEFAULT;

  /**
   * The cached value of the '{@link #getStatements() <em>Statements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatements()
   * @generated
   * @ordered
   */
  protected EList<AstStatement> statements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AstProcessDescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CalPackage.Literals.AST_PROCESS_DESCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isRepeated()
  {
    return repeated;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRepeated(boolean newRepeated)
  {
    boolean oldRepeated = repeated;
    repeated = newRepeated;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CalPackage.AST_PROCESS_DESCRIPTION__REPEATED, oldRepeated, repeated));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AstStatement> getStatements()
  {
    if (statements == null)
    {
      statements = new EObjectContainmentEList<AstStatement>(AstStatement.class, this, CalPackage.AST_PROCESS_DESCRIPTION__STATEMENTS);
    }
    return statements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CalPackage.AST_PROCESS_DESCRIPTION__STATEMENTS:
        return ((InternalEList<?>)getStatements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CalPackage.AST_PROCESS_DESCRIPTION__REPEATED:
        return isRepeated();
      case CalPackage.AST_PROCESS_DESCRIPTION__STATEMENTS:
        return getStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CalPackage.AST_PROCESS_DESCRIPTION__REPEATED:
        setRepeated((Boolean)newValue);
        return;
      case CalPackage.AST_PROCESS_DESCRIPTION__STATEMENTS:
        getStatements().clear();
        getStatements().addAll((Collection<? extends AstStatement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CalPackage.AST_PROCESS_DESCRIPTION__REPEATED:
        setRepeated(REPEATED_EDEFAULT);
        return;
      case CalPackage.AST_PROCESS_DESCRIPTION__STATEMENTS:
        getStatements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CalPackage.AST_PROCESS_DESCRIPTION__REPEATED:
        return repeated != REPEATED_EDEFAULT;
      case CalPackage.AST_PROCESS_DESCRIPTION__STATEMENTS:
        return statements != null && !statements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (repeated: ");
    result.append(repeated);
    result.append(')');
    return result.toString();
  }

} //AstProcessDescriptionImpl
