/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal.impl;

import org.eclipse.emf.ecore.EClass;

import streamblocks.eclipse.cal.cal.AstTuple;
import streamblocks.eclipse.cal.cal.CalPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ast Tuple</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AstTupleImpl extends AstTaggedTupleImpl implements AstTuple
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AstTupleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CalPackage.Literals.AST_TUPLE;
  }

} //AstTupleImpl
