/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal.impl;

import org.eclipse.emf.ecore.EClass;

import streamblocks.eclipse.cal.cal.CalPackage;
import streamblocks.eclipse.cal.cal.GroupImportTail;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Group Import Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GroupImportTailImpl extends ImportImpl implements GroupImportTail
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GroupImportTailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CalPackage.Literals.GROUP_IMPORT_TAIL;
  }

} //GroupImportTailImpl
