/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Abstract Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstAbstractActor#getName <em>Name</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstAbstractActor#getParameters <em>Parameters</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstAbstractActor#getInputs <em>Inputs</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstAbstractActor#getOutputs <em>Outputs</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstAbstractActor()
 * @model
 * @generated
 */
public interface AstAbstractActor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstAbstractActor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstAbstractActor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstAbstractActor_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getParameters();

  /**
   * Returns the value of the '<em><b>Inputs</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstPort}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inputs</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstAbstractActor_Inputs()
   * @model containment="true"
   * @generated
   */
  EList<AstPort> getInputs();

  /**
   * Returns the value of the '<em><b>Outputs</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstPort}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outputs</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstAbstractActor_Outputs()
   * @model containment="true"
   * @generated
   */
  EList<AstPort> getOutputs();

} // AstAbstractActor
