/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getFunctions <em>Functions</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getProcedures <em>Procedures</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getInvariants <em>Invariants</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getActions <em>Actions</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getProcesses <em>Processes</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getInitializes <em>Initializes</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getStateVariables <em>State Variables</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getSchedules <em>Schedules</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getScheduleRegExp <em>Schedule Reg Exp</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstActor#getPriorities <em>Priorities</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor()
 * @model
 * @generated
 */
public interface AstActor extends AstAbstractActor
{
  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Functions()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getFunctions();

  /**
   * Returns the value of the '<em><b>Procedures</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedures</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Procedures()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getProcedures();

  /**
   * Returns the value of the '<em><b>Invariants</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstInvariant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invariants</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Invariants()
   * @model containment="true"
   * @generated
   */
  EList<AstInvariant> getInvariants();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Actions()
   * @model containment="true"
   * @generated
   */
  EList<AstAction> getActions();

  /**
   * Returns the value of the '<em><b>Processes</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstProcessDescription}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processes</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Processes()
   * @model containment="true"
   * @generated
   */
  EList<AstProcessDescription> getProcesses();

  /**
   * Returns the value of the '<em><b>Initializes</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initializes</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Initializes()
   * @model containment="true"
   * @generated
   */
  EList<AstAction> getInitializes();

  /**
   * Returns the value of the '<em><b>State Variables</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Variables</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_StateVariables()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getStateVariables();

  /**
   * Returns the value of the '<em><b>Schedules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedules</em>' containment reference.
   * @see #setSchedules(AstSchedule)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Schedules()
   * @model containment="true"
   * @generated
   */
  AstSchedule getSchedules();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstActor#getSchedules <em>Schedules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schedules</em>' containment reference.
   * @see #getSchedules()
   * @generated
   */
  void setSchedules(AstSchedule value);

  /**
   * Returns the value of the '<em><b>Schedule Reg Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedule Reg Exp</em>' containment reference.
   * @see #setScheduleRegExp(RegExp)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_ScheduleRegExp()
   * @model containment="true"
   * @generated
   */
  RegExp getScheduleRegExp();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstActor#getScheduleRegExp <em>Schedule Reg Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schedule Reg Exp</em>' containment reference.
   * @see #getScheduleRegExp()
   * @generated
   */
  void setScheduleRegExp(RegExp value);

  /**
   * Returns the value of the '<em><b>Priorities</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstPriority}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priorities</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstActor_Priorities()
   * @model containment="true"
   * @generated
   */
  EList<AstPriority> getPriorities();

} // AstActor
