/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Expression List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionList#getExpressions <em>Expressions</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionList#getGenerators <em>Generators</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionList()
 * @model
 * @generated
 */
public interface AstExpressionList extends AstExpression
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionList_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<AstExpression> getExpressions();

  /**
   * Returns the value of the '<em><b>Generators</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstGenerator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generators</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionList_Generators()
   * @model containment="true"
   * @generated
   */
  EList<AstGenerator> getGenerators();

} // AstExpressionList
