/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast External Procedure</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExternalProcedure()
 * @model
 * @generated
 */
public interface AstExternalProcedure extends EObject
{
} // AstExternalProcedure
