/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Expression Alternative</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionAlternative#getPattern <em>Pattern</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionAlternative#getGuards <em>Guards</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionAlternative#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionAlternative()
 * @model
 * @generated
 */
public interface AstExpressionAlternative extends EObject
{
  /**
   * Returns the value of the '<em><b>Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' containment reference.
   * @see #setPattern(AstPattern)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionAlternative_Pattern()
   * @model containment="true"
   * @generated
   */
  AstPattern getPattern();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionAlternative#getPattern <em>Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' containment reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(AstPattern value);

  /**
   * Returns the value of the '<em><b>Guards</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guards</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionAlternative_Guards()
   * @model containment="true"
   * @generated
   */
  EList<AstExpression> getGuards();

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionAlternative_Expression()
   * @model containment="true"
   * @generated
   */
  AstExpression getExpression();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionAlternative#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(AstExpression value);

} // AstExpressionAlternative
