/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Entity If Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstEntityIfExpr#getCondition <em>Condition</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstEntityIfExpr#getTrueEntity <em>True Entity</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstEntityIfExpr#getFalseEntity <em>False Entity</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstEntityIfExpr()
 * @model
 * @generated
 */
public interface AstEntityIfExpr extends AstEntityExpr
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstEntityIfExpr_Condition()
   * @model containment="true"
   * @generated
   */
  AstExpression getCondition();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstEntityIfExpr#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(AstExpression value);

  /**
   * Returns the value of the '<em><b>True Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>True Entity</em>' containment reference.
   * @see #setTrueEntity(AstEntityExpr)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstEntityIfExpr_TrueEntity()
   * @model containment="true"
   * @generated
   */
  AstEntityExpr getTrueEntity();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstEntityIfExpr#getTrueEntity <em>True Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>True Entity</em>' containment reference.
   * @see #getTrueEntity()
   * @generated
   */
  void setTrueEntity(AstEntityExpr value);

  /**
   * Returns the value of the '<em><b>False Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>False Entity</em>' containment reference.
   * @see #setFalseEntity(AstEntityExpr)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstEntityIfExpr_FalseEntity()
   * @model containment="true"
   * @generated
   */
  AstEntityExpr getFalseEntity();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstEntityIfExpr#getFalseEntity <em>False Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>False Entity</em>' containment reference.
   * @see #getFalseEntity()
   * @generated
   */
  void setFalseEntity(AstEntityExpr value);

} // AstEntityIfExpr
