/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast External Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExternalActor()
 * @model
 * @generated
 */
public interface AstExternalActor extends AstAbstractActor
{
} // AstExternalActor
