/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Expression Assertion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionAssertion#getTarget <em>Target</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionAssertion#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionAssertion()
 * @model
 * @generated
 */
public interface AstExpressionAssertion extends AstExpression
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionAssertion_Target()
   * @model containment="true"
   * @generated
   */
  AstExpression getTarget();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionAssertion#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(AstExpression value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(AstType)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionAssertion_Type()
   * @model containment="true"
   * @generated
   */
  AstType getType();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionAssertion#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(AstType value);

} // AstExpressionAssertion
