/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Expression Unary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionUnary#getUnaryOperator <em>Unary Operator</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionUnary#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionUnary()
 * @model
 * @generated
 */
public interface AstExpressionUnary extends AstExpression
{
  /**
   * Returns the value of the '<em><b>Unary Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary Operator</em>' attribute.
   * @see #setUnaryOperator(String)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionUnary_UnaryOperator()
   * @model
   * @generated
   */
  String getUnaryOperator();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionUnary#getUnaryOperator <em>Unary Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary Operator</em>' attribute.
   * @see #getUnaryOperator()
   * @generated
   */
  void setUnaryOperator(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionUnary_Expression()
   * @model containment="true"
   * @generated
   */
  AstExpression getExpression();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionUnary#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(AstExpression value);

} // AstExpressionUnary
