/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Entity Instance Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstEntityInstanceExpr#getType <em>Type</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstEntityInstanceExpr#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstEntityInstanceExpr()
 * @model
 * @generated
 */
public interface AstEntityInstanceExpr extends AstEntityExpr
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(AstEntity)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstEntityInstanceExpr_Type()
   * @model
   * @generated
   */
  AstEntity getType();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstEntityInstanceExpr#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(AstEntity value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstAssignParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstEntityInstanceExpr_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<AstAssignParameter> getParameters();

} // AstEntityInstanceExpr
