/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Expression Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionLiteral()
 * @model
 * @generated
 */
public interface AstExpressionLiteral extends AstExpression
{
} // AstExpressionLiteral
