/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Expression Symbol Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getSymbol <em>Symbol</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getIndexes <em>Indexes</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getMember <em>Member</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getCtor <em>Ctor</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#isCall <em>Call</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference()
 * @model
 * @generated
 */
public interface AstExpressionSymbolReference extends AstExpression
{
  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstAnnotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<AstAnnotation> getAnnotations();

  /**
   * Returns the value of the '<em><b>Symbol</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol</em>' reference.
   * @see #setSymbol(AstVariable)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference_Symbol()
   * @model
   * @generated
   */
  AstVariable getSymbol();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getSymbol <em>Symbol</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol</em>' reference.
   * @see #getSymbol()
   * @generated
   */
  void setSymbol(AstVariable value);

  /**
   * Returns the value of the '<em><b>Indexes</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indexes</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference_Indexes()
   * @model containment="true"
   * @generated
   */
  EList<AstExpression> getIndexes();

  /**
   * Returns the value of the '<em><b>Member</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstMemberAccess}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference_Member()
   * @model containment="true"
   * @generated
   */
  EList<AstMemberAccess> getMember();

  /**
   * Returns the value of the '<em><b>Ctor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ctor</em>' attribute.
   * @see #setCtor(String)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference_Ctor()
   * @model
   * @generated
   */
  String getCtor();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#getCtor <em>Ctor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ctor</em>' attribute.
   * @see #getCtor()
   * @generated
   */
  void setCtor(String value);

  /**
   * Returns the value of the '<em><b>Call</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Call</em>' attribute.
   * @see #setCall(boolean)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference_Call()
   * @model
   * @generated
   */
  boolean isCall();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstExpressionSymbolReference#isCall <em>Call</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Call</em>' attribute.
   * @see #isCall()
   * @generated
   */
  void setCall(boolean value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstExpressionSymbolReference_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<AstExpression> getParameters();

} // AstExpressionSymbolReference
