/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Generator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstGenerator#getVariable <em>Variable</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstGenerator#getExpression <em>Expression</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstGenerator#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstGenerator()
 * @model
 * @generated
 */
public interface AstGenerator extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(AstVariable)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstGenerator_Variable()
   * @model containment="true"
   * @generated
   */
  AstVariable getVariable();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstGenerator#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(AstVariable value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstGenerator_Expression()
   * @model containment="true"
   * @generated
   */
  AstExpression getExpression();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstGenerator#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(AstExpression value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstGenerator_Filter()
   * @model containment="true"
   * @generated
   */
  EList<AstExpression> getFilter();

} // AstGenerator
