/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast LValue</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstLValue#getTarget <em>Target</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstLValue#getIndexes <em>Indexes</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstLValue#getMember <em>Member</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstLValue()
 * @model
 * @generated
 */
public interface AstLValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(AstVariable)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstLValue_Target()
   * @model
   * @generated
   */
  AstVariable getTarget();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstLValue#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(AstVariable value);

  /**
   * Returns the value of the '<em><b>Indexes</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indexes</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstLValue_Indexes()
   * @model containment="true"
   * @generated
   */
  EList<AstExpression> getIndexes();

  /**
   * Returns the value of the '<em><b>Member</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstMemberAccess}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstLValue_Member()
   * @model containment="true"
   * @generated
   */
  EList<AstMemberAccess> getMember();

} // AstLValue
