/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Namespace</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#isRvc <em>Rvc</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getName <em>Name</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getEntities <em>Entities</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getImports <em>Imports</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getUnits <em>Units</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getFunctions <em>Functions</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getProcedures <em>Procedures</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getVariables <em>Variables</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getExternals <em>Externals</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getTypedefs <em>Typedefs</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNamespace#getNamespaces <em>Namespaces</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace()
 * @model
 * @generated
 */
public interface AstNamespace extends CompilationUnit, AstPackage, AstUnit
{
  /**
   * Returns the value of the '<em><b>Rvc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rvc</em>' attribute.
   * @see #setRvc(boolean)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Rvc()
   * @model
   * @generated
   */
  boolean isRvc();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstNamespace#isRvc <em>Rvc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rvc</em>' attribute.
   * @see #isRvc()
   * @generated
   */
  void setRvc(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstNamespace#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstEntity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Entities()
   * @model containment="true"
   * @generated
   */
  EList<AstEntity> getEntities();

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Imports()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getImports();

  /**
   * Returns the value of the '<em><b>Units</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Units()
   * @model containment="true"
   * @generated
   */
  EList<AstUnit> getUnits();

  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Functions()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getFunctions();

  /**
   * Returns the value of the '<em><b>Procedures</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedures</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Procedures()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getProcedures();

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Variables()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getVariables();

  /**
   * Returns the value of the '<em><b>Externals</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Externals</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Externals()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getExternals();

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstAnnotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<AstAnnotation> getAnnotations();

  /**
   * Returns the value of the '<em><b>Typedefs</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstTypeUser}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typedefs</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Typedefs()
   * @model containment="true"
   * @generated
   */
  EList<AstTypeUser> getTypedefs();

  /**
   * Returns the value of the '<em><b>Namespaces</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstNamespace}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Namespaces</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNamespace_Namespaces()
   * @model containment="true"
   * @generated
   */
  EList<AstNamespace> getNamespaces();

} // AstNamespace
