/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Network</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNetwork#getVariables <em>Variables</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNetwork#getEntities <em>Entities</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstNetwork#getStructure <em>Structure</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNetwork()
 * @model
 * @generated
 */
public interface AstNetwork extends AstAbstractActor
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNetwork_Variables()
   * @model containment="true"
   * @generated
   */
  EList<AstVariable> getVariables();

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstEntityVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNetwork_Entities()
   * @model containment="true"
   * @generated
   */
  EList<AstEntityVariable> getEntities();

  /**
   * Returns the value of the '<em><b>Structure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structure</em>' containment reference.
   * @see #setStructure(AstStructure)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstNetwork_Structure()
   * @model containment="true"
   * @generated
   */
  AstStructure getStructure();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstNetwork#getStructure <em>Structure</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Structure</em>' containment reference.
   * @see #getStructure()
   * @generated
   */
  void setStructure(AstStructure value);

} // AstNetwork
