/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstPattern#getVariable <em>Variable</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstPattern#getPatterns <em>Patterns</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstPattern#getAlias <em>Alias</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstPattern#getExpression <em>Expression</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstPattern#getLiteral <em>Literal</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstPattern#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstPattern()
 * @model
 * @generated
 */
public interface AstPattern extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(AstVariable)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstPattern_Variable()
   * @model containment="true"
   * @generated
   */
  AstVariable getVariable();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstPattern#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(AstVariable value);

  /**
   * Returns the value of the '<em><b>Patterns</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstPattern}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patterns</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstPattern_Patterns()
   * @model containment="true"
   * @generated
   */
  EList<AstPattern> getPatterns();

  /**
   * Returns the value of the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' containment reference.
   * @see #setAlias(AstPattern)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstPattern_Alias()
   * @model containment="true"
   * @generated
   */
  AstPattern getAlias();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstPattern#getAlias <em>Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' containment reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(AstPattern value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(EObject)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstPattern_Expression()
   * @model containment="true"
   * @generated
   */
  EObject getExpression();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstPattern#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(EObject value);

  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference.
   * @see #setLiteral(AstExpressionLiteral)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstPattern_Literal()
   * @model containment="true"
   * @generated
   */
  AstExpressionLiteral getLiteral();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstPattern#getLiteral <em>Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' containment reference.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(AstExpressionLiteral value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstPattern_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstPattern#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // AstPattern
