/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Statement Alternative</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementAlternative#getPattern <em>Pattern</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementAlternative#getGuards <em>Guards</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementAlternative#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementAlternative()
 * @model
 * @generated
 */
public interface AstStatementAlternative extends EObject
{
  /**
   * Returns the value of the '<em><b>Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' containment reference.
   * @see #setPattern(AstPattern)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementAlternative_Pattern()
   * @model containment="true"
   * @generated
   */
  AstPattern getPattern();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstStatementAlternative#getPattern <em>Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' containment reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(AstPattern value);

  /**
   * Returns the value of the '<em><b>Guards</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guards</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementAlternative_Guards()
   * @model containment="true"
   * @generated
   */
  EList<AstExpression> getGuards();

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementAlternative_Statements()
   * @model containment="true"
   * @generated
   */
  EList<AstStatement> getStatements();

} // AstStatementAlternative
