/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Structure Statement If</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStructureStatementIf#getCondition <em>Condition</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStructureStatementIf#getThen <em>Then</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStructureStatementIf#getElsifs <em>Elsifs</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStructureStatementIf#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStructureStatementIf()
 * @model
 * @generated
 */
public interface AstStructureStatementIf extends AstStructureStatement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStructureStatementIf_Condition()
   * @model containment="true"
   * @generated
   */
  AstExpression getCondition();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstStructureStatementIf#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(AstExpression value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstStructureStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStructureStatementIf_Then()
   * @model containment="true"
   * @generated
   */
  EList<AstStructureStatement> getThen();

  /**
   * Returns the value of the '<em><b>Elsifs</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstStructureStatementElsif}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elsifs</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStructureStatementIf_Elsifs()
   * @model containment="true"
   * @generated
   */
  EList<AstStructureStatementElsif> getElsifs();

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstStructureStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStructureStatementIf_Else()
   * @model containment="true"
   * @generated
   */
  EList<AstStructureStatement> getElse();

} // AstStructureStatementIf
