/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Statement Read</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementRead#getPort <em>Port</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementRead#getLvalues <em>Lvalues</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementRead#getRepeat <em>Repeat</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementRead()
 * @model
 * @generated
 */
public interface AstStatementRead extends AstStatement
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' reference.
   * @see #setPort(AstPort)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementRead_Port()
   * @model
   * @generated
   */
  AstPort getPort();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstStatementRead#getPort <em>Port</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' reference.
   * @see #getPort()
   * @generated
   */
  void setPort(AstPort value);

  /**
   * Returns the value of the '<em><b>Lvalues</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstLValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lvalues</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementRead_Lvalues()
   * @model containment="true"
   * @generated
   */
  EList<AstLValue> getLvalues();

  /**
   * Returns the value of the '<em><b>Repeat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repeat</em>' containment reference.
   * @see #setRepeat(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementRead_Repeat()
   * @model containment="true"
   * @generated
   */
  AstExpression getRepeat();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstStatementRead#getRepeat <em>Repeat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repeat</em>' containment reference.
   * @see #getRepeat()
   * @generated
   */
  void setRepeat(AstExpression value);

} // AstStatementRead
