/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Statement Assign</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementAssign#getLvalue <em>Lvalue</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstStatementAssign#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementAssign()
 * @model
 * @generated
 */
public interface AstStatementAssign extends AstStatement
{
  /**
   * Returns the value of the '<em><b>Lvalue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lvalue</em>' containment reference.
   * @see #setLvalue(AstLValue)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementAssign_Lvalue()
   * @model containment="true"
   * @generated
   */
  AstLValue getLvalue();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstStatementAssign#getLvalue <em>Lvalue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lvalue</em>' containment reference.
   * @see #getLvalue()
   * @generated
   */
  void setLvalue(AstLValue value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(AstExpression)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstStatementAssign_Value()
   * @model containment="true"
   * @generated
   */
  AstExpression getValue();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstStatementAssign#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(AstExpression value);

} // AstStatementAssign
