/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Tuple</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstTuple()
 * @model
 * @generated
 */
public interface AstTuple extends AstTaggedTuple
{
} // AstTuple
