/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ast Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstTransition#getSource <em>Source</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstTransition#getTags <em>Tags</em>}</li>
 *   <li>{@link streamblocks.eclipse.cal.cal.AstTransition#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getAstTransition()
 * @model
 * @generated
 */
public interface AstTransition extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(AstState)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstTransition_Source()
   * @model
   * @generated
   */
  AstState getSource();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstTransition#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(AstState value);

  /**
   * Returns the value of the '<em><b>Tags</b></em>' containment reference list.
   * The list contents are of type {@link streamblocks.eclipse.cal.cal.AstTag}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' containment reference list.
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstTransition_Tags()
   * @model containment="true"
   * @generated
   */
  EList<AstTag> getTags();

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(AstState)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getAstTransition_Target()
   * @model
   * @generated
   */
  AstState getTarget();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.AstTransition#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(AstState value);

} // AstTransition
