/**
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.cal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Import Tail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link streamblocks.eclipse.cal.cal.SingleImportTail#getLocalNameToken <em>Local Name Token</em>}</li>
 * </ul>
 *
 * @see streamblocks.eclipse.cal.cal.CalPackage#getSingleImportTail()
 * @model
 * @generated
 */
public interface SingleImportTail extends Import
{
  /**
   * Returns the value of the '<em><b>Local Name Token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local Name Token</em>' attribute.
   * @see #setLocalNameToken(String)
   * @see streamblocks.eclipse.cal.cal.CalPackage#getSingleImportTail_LocalNameToken()
   * @model
   * @generated
   */
  String getLocalNameToken();

  /**
   * Sets the value of the '{@link streamblocks.eclipse.cal.cal.SingleImportTail#getLocalNameToken <em>Local Name Token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local Name Token</em>' attribute.
   * @see #getLocalNameToken()
   * @generated
   */
  void setLocalNameToken(String value);

} // SingleImportTail
