/*
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link CalWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractCalWebModule extends DefaultWebModule {

}
