/*
 * generated by Xtext 2.21.0
 */
package streamblocks.eclipse.cal.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCalValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(streamblocks.eclipse.cal.cal.CalPackage.eINSTANCE);
		return result;
	}
}
